id: P004514
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2423
  title: ཞང་ཞུང་ཆོས་དབང་གྲགས་པའི་བསྟོད་ཚོགས
  author: ''
  volumes:
    28a50e0340884809971b316a197a99ea:
      image_group_id: I1CZ2472
      title: ''
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
